#ifndef LIBPASSION_INCLUDE_MODULES_GRAPHICS_PS_GRAPHICS_SYSTEM_INFORMATION_H_
#define LIBPASSION_INCLUDE_MODULES_GRAPHICS_PS_GRAPHICS_SYSTEM_INFORMATION_H_
#include "../utils/ps_api.h"
#include "../utils/ps_status.h"

#endif