#ifndef LIBPASSION_INCLUDE_MODULES_GRAPHICS_PS_LINE_JOIN_H_
#define LIBPASSION_INCLUDE_MODULES_GRAPHICS_PS_LINE_JOIN_H_

enum ps_line_join {
        PS_LINE_JOIN_MITER,
        PS_LINE_JONI_NONE,
        PS_LINE_JOIN_BEVEL
};

#endif