#ifndef LIBPASSION_INCLUDE_MODULES_GRAPHICS_PS_LINE_STYLE_H_
#define LIBPASSION_INCLUDE_MODULES_GRAPHICS_PS_LINE_STYLE_H_

enum ps_line_style {
        PS_LINE_STYLE_ROUGH,
        PS_LINE_STYLE_SMOOTH
};

#endif