#ifndef LIBPASSION_INCLUDE_MODULES_GRAPHICS_PS_STACK_TYPE_H_
#define LIBPASSION_INCLUDE_MODULES_GRAPHICS_PS_STACK_TYPE_H_

enum ps_stack_type {
        PS_STACK_TYPE_TRANSFORM,
        PS_STACK_TYPE_ALL
};

#endif