#ifndef LIBPASSION_INCLUDE_MODULES_GRAPHICS_PS_VERTEX_ATTRIB_ID_H_
#define LIBPASSION_INCLUDE_MODULES_GRAPHICS_PS_VERTEX_ATTRIB_ID_H_

enum ps_vertex_attrib_id {
        PS_VERTEX_ATTRIB_POS,
        PS_VERTEX_ATTRIB_TEXCOORD,
        PS_VERTEX_ATTRIB_COLOR,
        PS_VERTEX_ATTRIB_CONSTANT_COLOR
};

#endif