#ifndef LIBPASSION_INCLUDE_MODULES_WINDOW_PS_FULLSCREEN_TYPE_H_
#define LIBPASSION_INCLUDE_MODULES_WINDOW_PS_FULLSCREEN_TYPE_H_

enum ps_fullscreen_type {
        PS_FULLSCREEN_TYPE_DESKTOP,
        PS_FULLSCREEN_TYPE_NORMAL,
};

#endif