#ifndef LIBPASSION_INCLUDE_MODULES_SYSTEM_PS_POWERSTATE_H_
#define LIBPASSION_INCLUDE_MODULES_SYSTEM_PS_POWERSTATE_H_

enum ps_power_state {
        PS_POWER_STATE_UNKNOWN,
        PS_POWER_STATE_BATTERY,
        PS_POWER_STATE_NOBATTERY,
        PS_POWER_STATE_CHARGING,
        PS_POWER_STATE_CHARGED
};

#endif
