#ifndef LIBPASSION_INCLUDE_MODULES_PS_FILESYSTEM_PS_FILEDECODER_H_
#define LIBPASSION_INCLUDE_MODULES_PS_FILESYSTEM_PS_FILEDECODER_H_
#include <stdint.h>

typedef uint8_t ps_filedecoder;

enum PS_FILEDECODER {
        PS_FILEDECODER_FILE,
        PS_FILEDECODER_BASE64
};

#endif