#ifndef LIBPASSION_INCLUDE_MODULES_PS_EVENT_PS_MOUSE_BUTTON_H_
#define LIBPASSION_INCLUDE_MODULES_PS_EVENT_PS_MOUSE_BUTTON_H_

enum ps_mouse_button {
      PS_MOUSE_BUTTON_LEFT = 1,
      PS_MOUSE_BUTTON_MIDDLE = 2,
      PS_MOUSE_BUTTON_RIGHT = 3,
      PS_MOUSE_BUTTON_X1 = 4,
      PS_MOUSE_BUTTON_X2 = 5
};

#endif
