#ifndef LIBPASSION_INCLUDE_MODULES_PS_EVENT_PS_EVENT_TYPE_H_
#define LIBPASSION_INCLUDE_MODULES_PS_EVENT_PS_EVENT_TYPE_H_

enum ps_event_type {
        PS_EVENT_BREAK_POLLING = -1,
        PS_EVENT_UNKNOWN = 0,

        PS_EVENT_QUIT,

        PS_EVENT_FOCUS,

        PS_EVENT_KEYPRESSED,
        PS_EVENT_KEYRELEASED,

        PS_EVENT_MOUSEFOCUS,
        PS_EVENT_MOUSEMOVED,
        PS_EVENT_MOUSEPRESSED,
        PS_EVENT_MOUSERELEASED,

        PS_EVENT_RESIZE,
        PS_EVENT_VISIBLE,

        PS_EVENT_MAX
};

#endif