#ifndef LIBPASSION_INCLUDE_MODULES_PS_EVENT_PS_KEYCODE_H_
#define LIBPASSION_INCLUDE_MODULES_PS_EVENT_PS_KEYCODE_H_

#include "ps_scancode.h"

#define PS_KEY_SCANCODE_MASK (1<<30)
#define PS_SCANCODE_TO_KEYCODE(X)  (X | PS_KEY_SCANCODE_MASK)

enum ps_keycode {
        PS_KEYCODE_UNKNOWN = 0,

        PS_KEYCODE_RETURN = '\r',
        PS_KEYCODE_ESCAPE = '\033',
        PS_KEYCODE_BACKSPACE = '\b',
        PS_KEYCODE_TAB = '\t',
        PS_KEYCODE_SPACE = ' ',
        PS_KEYCODE_EXCLAIM = '!',
        PS_KEYCODE_QUOTEDBL = '"',
        PS_KEYCODE_HASH = '#',
        PS_KEYCODE_PERCENT = '%',
        PS_KEYCODE_DOLLAR = '$',
        PS_KEYCODE_AMPERSAND = '&',
        PS_KEYCODE_QUOTE = '\'',
        PS_KEYCODE_LEFTPAREN = '(',
        PS_KEYCODE_RIGHTPAREN = ')',
        PS_KEYCODE_ASTERISK = '*',
        PS_KEYCODE_PLUS = '+',
        PS_KEYCODE_COMMA = ',',
        PS_KEYCODE_MINUS = '-',
        PS_KEYCODE_PERIOD = '.',
        PS_KEYCODE_SLASH = '/',
        PS_KEYCODE_0 = '0',
        PS_KEYCODE_1 = '1',
        PS_KEYCODE_2 = '2',
        PS_KEYCODE_3 = '3',
        PS_KEYCODE_4 = '4',
        PS_KEYCODE_5 = '5',
        PS_KEYCODE_6 = '6',
        PS_KEYCODE_7 = '7',
        PS_KEYCODE_8 = '8',
        PS_KEYCODE_9 = '9',
        PS_KEYCODE_COLON = ':',
        PS_KEYCODE_SEMICOLON = ';',
        PS_KEYCODE_LESS = '<',
        PS_KEYCODE_EQUALS = '=',
        PS_KEYCODE_GREATER = '>',
        PS_KEYCODE_QUESTION = '?',
        PS_KEYCODE_AT = '@',
        /*
        Skip uppercase letters
        */
        PS_KEYCODE_LEFTBRACKET = '[',
        PS_KEYCODE_BACKSLASH = '\\',
        PS_KEYCODE_RIGHTBRACKET = ']',
        PS_KEYCODE_CARET = '^',
        PS_KEYCODE_UNDERSCORE = '_',
        PS_KEYCODE_BACKQUOTE = '`',
        PS_KEYCODE_A = 'a',
        PS_KEYCODE_B = 'b',
        PS_KEYCODE_C = 'c',
        PS_KEYCODE_D = 'd',
        PS_KEYCODE_E = 'e',
        PS_KEYCODE_F = 'f',
        PS_KEYCODE_G = 'g',
        PS_KEYCODE_H = 'h',
        PS_KEYCODE_I = 'i',
        PS_KEYCODE_J = 'j',
        PS_KEYCODE_K = 'k',
        PS_KEYCODE_L = 'l',
        PS_KEYCODE_M = 'm',
        PS_KEYCODE_N = 'n',
        PS_KEYCODE_O = 'o',
        PS_KEYCODE_P = 'p',
        PS_KEYCODE_Q = 'q',
        PS_KEYCODE_R = 'r',
        PS_KEYCODE_S = 's',
        PS_KEYCODE_T = 't',
        PS_KEYCODE_U = 'u',
        PS_KEYCODE_V = 'v',
        PS_KEYCODE_W = 'w',
        PS_KEYCODE_X = 'x',
        PS_KEYCODE_Y = 'y',
        PS_KEYCODE_Z = 'z',

        PS_KEYCODE_CAPSLOCK = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_CAPSLOCK),

        PS_KEYCODE_F1 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F1),
        PS_KEYCODE_F2 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F2),
        PS_KEYCODE_F3 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F3),
        PS_KEYCODE_F4 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F4),
        PS_KEYCODE_F5 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F5),
        PS_KEYCODE_F6 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F6),
        PS_KEYCODE_F7 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F7),
        PS_KEYCODE_F8 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F8),
        PS_KEYCODE_F9 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F9),
        PS_KEYCODE_F10 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F10),
        PS_KEYCODE_F11 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F11),
        PS_KEYCODE_F12 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F12),

        PS_KEYCODE_PRINTSCREEN = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_PRINTSCREEN),
        PS_KEYCODE_SCROLLLOCK = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_SCROLLLOCK),
        PS_KEYCODE_PAUSE = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_PAUSE),
        PS_KEYCODE_INSERT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_INSERT),
        PS_KEYCODE_HOME = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_HOME),
        PS_KEYCODE_PAGEUP = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_PAGEUP),
        PS_KEYCODE_DELETE = '\177',
        PS_KEYCODE_END = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_END),
        PS_KEYCODE_PAGEDOWN = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_PAGEDOWN),
        PS_KEYCODE_RIGHT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_RIGHT),
        PS_KEYCODE_LEFT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_LEFT),
        PS_KEYCODE_DOWN = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_DOWN),
        PS_KEYCODE_UP = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_UP),

        PS_KEYCODE_NUMLOCKCLEAR = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_NUMLOCKCLEAR),
        PS_KEYCODE_KP_DIVIDE = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_DIVIDE),
        PS_KEYCODE_KP_MULTIPLY = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_MULTIPLY),
        PS_KEYCODE_KP_MINUS = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_MINUS),
        PS_KEYCODE_KP_PLUS = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_PLUS),
        PS_KEYCODE_KP_ENTER = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_ENTER),
        PS_KEYCODE_KP_1 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_1),
        PS_KEYCODE_KP_2 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_2),
        PS_KEYCODE_KP_3 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_3),
        PS_KEYCODE_KP_4 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_4),
        PS_KEYCODE_KP_5 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_5),
        PS_KEYCODE_KP_6 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_6),
        PS_KEYCODE_KP_7 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_7),
        PS_KEYCODE_KP_8 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_8),
        PS_KEYCODE_KP_9 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_9),
        PS_KEYCODE_KP_0 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_0),
        PS_KEYCODE_KP_PERIOD = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_PERIOD),

        PS_KEYCODE_APPLICATION = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_APPLICATION),
        PS_KEYCODE_POWER = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_POWER),
        PS_KEYCODE_KP_EQUALS = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_EQUALS),
        PS_KEYCODE_F13 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F13),
        PS_KEYCODE_F14 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F14),
        PS_KEYCODE_F15 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F15),
        PS_KEYCODE_F16 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F16),
        PS_KEYCODE_F17 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F17),
        PS_KEYCODE_F18 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F18),
        PS_KEYCODE_F19 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F19),
        PS_KEYCODE_F20 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F20),
        PS_KEYCODE_F21 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F21),
        PS_KEYCODE_F22 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F22),
        PS_KEYCODE_F23 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F23),
        PS_KEYCODE_F24 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_F24),
        PS_KEYCODE_EXECUTE = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_EXECUTE),
        PS_KEYCODE_HELP = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_HELP),
        PS_KEYCODE_MENU = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_MENU),
        PS_KEYCODE_SELECT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_SELECT),
        PS_KEYCODE_STOP = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_STOP),
        PS_KEYCODE_AGAIN = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AGAIN),
        PS_KEYCODE_UNDO = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_UNDO),
        PS_KEYCODE_CUT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_CUT),
        PS_KEYCODE_COPY = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_COPY),
        PS_KEYCODE_PASTE = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_PASTE),
        PS_KEYCODE_FIND = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_FIND),
        PS_KEYCODE_MUTE = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_MUTE),
        PS_KEYCODE_VOLUMEUP = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_VOLUMEUP),
        PS_KEYCODE_VOLUMEDOWN = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_VOLUMEDOWN),
        PS_KEYCODE_KP_COMMA = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_COMMA),
        PS_KEYCODE_KP_EQUALSAS400 =
        PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_EQUALSAS400),

        PS_KEYCODE_ALTERASE = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_ALTERASE),
        PS_KEYCODE_SYSREQ = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_SYSREQ),
        PS_KEYCODE_CANCEL = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_CANCEL),
        PS_KEYCODE_CLEAR = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_CLEAR),
        PS_KEYCODE_PRIOR = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_PRIOR),
        PS_KEYCODE_RETURN2 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_RETURN2),
        PS_KEYCODE_SEPARATOR = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_SEPARATOR),
        PS_KEYCODE_OUT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_OUT),
        PS_KEYCODE_OPER = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_OPER),
        PS_KEYCODE_CLEARAGAIN = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_CLEARAGAIN),
        PS_KEYCODE_CRSEL = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_CRSEL),
        PS_KEYCODE_EXSEL = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_EXSEL),

        PS_KEYCODE_KP_00 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_00),
        PS_KEYCODE_KP_000 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_000),
        PS_KEYCODE_THOUSANDSSEPARATOR =
        PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_THOUSANDSSEPARATOR),
        PS_KEYCODE_DECIMALSEPARATOR =
        PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_DECIMALSEPARATOR),
        PS_KEYCODE_CURRENCYUNIT = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_CURRENCYUNIT),
        PS_KEYCODE_CURRENCYSUBUNIT =
        PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_CURRENCYSUBUNIT),
        PS_KEYCODE_KP_LEFTPAREN = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_LEFTPAREN),
        PS_KEYCODE_KP_RIGHTPAREN = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_RIGHTPAREN),
        PS_KEYCODE_KP_LEFTBRACE = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_LEFTBRACE),
        PS_KEYCODE_KP_RIGHTBRACE = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_RIGHTBRACE),
        PS_KEYCODE_KP_TAB = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_TAB),
        PS_KEYCODE_KP_BACKSPACE =
                        PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_BACKSPACE),
        PS_KEYCODE_KP_A = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_A),
        PS_KEYCODE_KP_B = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_B),
        PS_KEYCODE_KP_C = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_C),
        PS_KEYCODE_KP_D = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_D),
        PS_KEYCODE_KP_E = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_E),
        PS_KEYCODE_KP_F = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_F),
        PS_KEYCODE_KP_XOR = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_XOR),
        PS_KEYCODE_KP_POWER = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_POWER),
        PS_KEYCODE_KP_PERCENT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_PERCENT),
        PS_KEYCODE_KP_LESS = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_LESS),
        PS_KEYCODE_KP_GREATER = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_GREATER),
        PS_KEYCODE_KP_AMPERSAND = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_AMPERSAND),
        PS_KEYCODE_KP_DBLAMPERSAND =
        PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_DBLAMPERSAND),
        PS_KEYCODE_KP_VERTICALBAR =
        PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_VERTICALBAR),
        PS_KEYCODE_KP_DBLVERTICALBAR =
        PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_DBLVERTICALBAR),
        PS_KEYCODE_KP_COLON = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_COLON),
        PS_KEYCODE_KP_HASH = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_HASH),
        PS_KEYCODE_KP_SPACE = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_SPACE),
        PS_KEYCODE_KP_AT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_AT),
        PS_KEYCODE_KP_EXCLAM = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_EXCLAM),
        PS_KEYCODE_KP_MEMSTORE = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_MEMSTORE),
        PS_KEYCODE_KP_MEMRECALL = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_MEMRECALL),
        PS_KEYCODE_KP_MEMCLEAR = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_MEMCLEAR),
        PS_KEYCODE_KP_MEMADD = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_MEMADD),
        PS_KEYCODE_KP_MEMSUBTRACT =
        PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_MEMSUBTRACT),
        PS_KEYCODE_KP_MEMMULTIPLY =
        PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_MEMMULTIPLY),
        PS_KEYCODE_KP_MEMDIVIDE = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_MEMDIVIDE),
        PS_KEYCODE_KP_PLUSMINUS = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_PLUSMINUS),
        PS_KEYCODE_KP_CLEAR = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_CLEAR),
        PS_KEYCODE_KP_CLEARENTRY = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_CLEARENTRY),
        PS_KEYCODE_KP_BINARY = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_BINARY),
        PS_KEYCODE_KP_OCTAL = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_OCTAL),
        PS_KEYCODE_KP_DECIMAL = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_DECIMAL),
        PS_KEYCODE_KP_HEXADECIMAL =
        PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KP_HEXADECIMAL),

        PS_KEYCODE_LCTRL = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_LCTRL),
        PS_KEYCODE_LSHIFT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_LSHIFT),
        PS_KEYCODE_LALT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_LALT),
        PS_KEYCODE_LGUI = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_LGUI),
        PS_KEYCODE_RCTRL = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_RCTRL),
        PS_KEYCODE_RSHIFT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_RSHIFT),
        PS_KEYCODE_RALT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_RALT),
        PS_KEYCODE_RGUI = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_RGUI),

        PS_KEYCODE_MODE = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_MODE),

        PS_KEYCODE_AUDIONEXT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AUDIONEXT),
        PS_KEYCODE_AUDIOPREV = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AUDIOPREV),
        PS_KEYCODE_AUDIOSTOP = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AUDIOSTOP),
        PS_KEYCODE_AUDIOPLAY = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AUDIOPLAY),
        PS_KEYCODE_AUDIOMUTE = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AUDIOMUTE),
        PS_KEYCODE_MEDIASELECT = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_MEDIASELECT),
        PS_KEYCODE_WWW = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_WWW),
        PS_KEYCODE_MAIL = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_MAIL),
        PS_KEYCODE_CALCULATOR = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_CALCULATOR),
        PS_KEYCODE_COMPUTER = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_COMPUTER),
        PS_KEYCODE_AC_SEARCH = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AC_SEARCH),
        PS_KEYCODE_AC_HOME = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AC_HOME),
        PS_KEYCODE_AC_BACK = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AC_BACK),
        PS_KEYCODE_AC_FORWARD = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AC_FORWARD),
        PS_KEYCODE_AC_STOP = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AC_STOP),
        PS_KEYCODE_AC_REFRESH = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AC_REFRESH),
        PS_KEYCODE_AC_BOOKMARKS = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AC_BOOKMARKS),

        PS_KEYCODE_BRIGHTNESSDOWN =
        PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_BRIGHTNESSDOWN),
        PS_KEYCODE_BRIGHTNESSUP = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_BRIGHTNESSUP),
        PS_KEYCODE_DISPLAYSWITCH = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_DISPLAYSWITCH),
        PS_KEYCODE_KBDILLUMTOGGLE =
        PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KBDILLUMTOGGLE),
        PS_KEYCODE_KBDILLUMDOWN = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KBDILLUMDOWN),
        PS_KEYCODE_KBDILLUMUP = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_KBDILLUMUP),
        PS_KEYCODE_EJECT = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_EJECT),
        PS_KEYCODE_SLEEP = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_SLEEP),
        PS_KEYCODE_APP1 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_APP1),
        PS_KEYCODE_APP2 = PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_APP2),

        PS_KEYCODE_AUDIOREWIND = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AUDIOREWIND),
        PS_KEYCODE_AUDIOFASTFORWARD = 
                PS_SCANCODE_TO_KEYCODE(PS_SCANCODE_AUDIOFASTFORWARD)
};

#endif
